### PR TITLE
Use vec in metadata, instead of HashMap

### PR DESCRIPTION
**Pull request by kngwyu**

### CODE REVIEW

**Comment by jens1o** [comment]
is this faster?

**Comment by kngwyu** [comment]
Maybe so but I've not benched yet

**Comment by jens1o** [comment]
Were you able to bench this?

**Comment by kngwyu** [comment]
This PR is for #916 and not for speed.
But I benched just in case.
Before:
```
running 2 tests
test completes_rand  ... bench:  41,524,148 ns/iter (+/- 4,226,141)
test completes_rayon ... bench:  19,116,569 ns/iter (+/- 2,537,437)
```
After:
```
test completes_rand  ... bench:  40,405,594 ns/iter (+/- 1,842,591)
test completes_rayon ... bench:  16,894,357 ns/iter (+/- 2,034,093)
```
(Core i5-6500, Arch Linux 4.18.9)

**Pull request merged**
