### PR TITLE
Suggest to use the official vscode extension.

### PR DESCRIPTION
**Pull request by jens1o**

### CODE REVIEW

**Comment by kngwyu** [comment]
I don't know much about `vscode-rust`.
Are you sure we should remove it?

**Comment by jens1o** [comment]
Yeah, because it is no longer maintained. On the other hand, the underlying service of vscode-rust (rls) is updated constantly, and the vscode extension itself also gets some updates, if necessary.

**Comment by kngwyu** [comment]
Thanks, I decided to merge your PR.

**Comment by jens1o** [comment]
Thank you very much!

**Pull request merged**
