### PR TITLE
Bump version to 2.1.34

### PR DESCRIPTION
**Pull request by kngwyu**
cc: @topecongiro

### CODE REVIEW

**Comment by kngwyu** [comment]
CI fails due to the recent breaking change around `asm!`.
Maybe we need newer version of rustc-ap-*?

**Comment by Xanewok** [comment]
Needs #1112 to fix the nightly build

**Comment by Xanewok** [comment]
Let me know once you release the 2.1.34 with the fix so I can coordinate the update with RLS/rustfmt

**Comment by kngwyu** [comment]
@Xanewok 
Thank you! I relased it now.

**Pull request merged**
