### PR TITLE
Pass frozen=true flag to cargo by default to avoid network access

### PR DESCRIPTION
**Pull request by kngwyu**
To prevent internet access.
Though sometimes it may be convenient if racer can download dependencies, I think racer should lightweight tool for now.

### CODE REVIEW

**Comment by TedDriggs** [comment]
Can you please provide a better writeup of when racer would have gone to the network previously? I'm worried this will increase completion failure rates without people knowing it.

**Comment by kngwyu** [comment]
> Can you please provide a better writeup of when racer would have gone to the network previously?

Sure. Currently, racer downloads a dependency when **there's no specific version of package in local registry**.
So, basically if one add a dependency to `Cargo.toml` and not rebuild it yet, racer downloads it.
It may be convenient, but it can cause significant delay of completion when one's network accesses is unstable.

> I'm worried this will increase completion failure rates without people knowing it.

Yeah, but since the #855 version of racer is not yet released, we don't have to be too nervous about it.

**Comment by kngwyu** [comment]
I wrote some notes in #876

**Comment by kngwyu** [comment]
I found this PR make impossible to get completion via crates-io.patch.... :cold_sweat:

**Pull request merged**
