### PR TITLE
Add rust-toolchain file

### PR DESCRIPTION
**Pull request by svenstaro**
This makes sure that people will always have the correct nightly build that this works with. It also makes sure the build is reproducible (as different nightly version might behave differently).

### CODE REVIEW

**Comment by kngwyu** [comment]
Thanks, but I fear it can be outdated too quickly. Maybe binary release (#1119) is better.

**Comment by svenstaro** [comment]
I still think it would make a lot of sense in terms of reproducibility for distro packagers like me. Maybe consider maintaining a `rust-toolchain` in the future. :)

Probably it doesn't get outdated _that_ quickly.

**Comment by kngwyu** [comment]
OK, now I think I understand the merit and decided to merge this for now, though I'm not sure I can handle this effectively.

**Comment by svenstaro** [comment]
Sadly and ironically, as it turns out, the particular version 2020-07-21 [is broken](https://github.com/rust-lang/rust/issues/74577). I'm using nightly-2020-07-20 and that works fine.

**Pull request merged**
