### PR TITLE
bump rustc-ap-* crates to v664

### PR DESCRIPTION
**Pull request by calebcartwright**
Updated needed as part of fixing broken toolstate for rls and rustfmt

Refs:
* https://github.com/rust-lang/rust/issues/73199
* https://github.com/rust-lang/rust/issues/73200
* https://github.com/rust-lang/rustfmt/pull/4253

cc @topecongiro @Xanewok

### CODE REVIEW

**Comment by calebcartwright** [comment]
Travis job failed due to timeout, seems to be an existing issue

https://travis-ci.org/github/racer-rust/racer/pull_requests

**Comment by kngwyu** [comment]
Thanks!

**Comment by kngwyu** [comment]
Released v2.1.35 now.

**Comment by calebcartwright** [comment]
Thank you!

**Pull request merged**
