### PR TITLE
Implement completion for struct impls defined in submodules

### PR DESCRIPTION
**Pull request by ReeceStevens**
See issue #771

### CODE REVIEW

**Comment by ReeceStevens** [comment]
I'm still working on a solution for this, but I wanted to get a PR up early in case anybody had comments or suggestions on how to proceed with this ticket.

**Comment by bkchr** [comment]
Hi, I just looked at the implementation and did not test anything, but I assume that the following call https://github.com/ReeceStevens/racer/blob/c615f7766ec34b9fce4a3a17af5bc4f769e83961/src/racer/nameres.rs#L254 does not return true. I would start to look there :)

**Comment by bkchr** [comment]
Forget what I said... :( 
Maybe you should look at the blobs and see, in the first place, if the code finds the impl block at all.

**Comment by ReeceStevens** [comment]
@bkchr thanks for the response! @TedDriggs suggested I look through the debug logs and start there, so that's where the investigation shall begin. I'll probably keep discussion on the issue until there's some semblance of a reviewable PR here :)

**Comment by jwilm** [comment]
Removed the `needs review` label until it's not `not ready`. :wink:

**Comment by TedDriggs** [comment]
Last I heard, @ReeceStevens was pursuing an alternate solution to his particular problem with the specific library he's trying to use.

**Comment by ReeceStevens** [comment]
Hey @TedDriggs sorry for the delay in getting back to you. The alternate solution you suggested worked well and I will be opening a PR on `svd2rust` soon. Thanks for your help :)

**Pull request closed without merging**
