### PR TITLE
 Do not convert iterator until it actually treats iterator

### PR DESCRIPTION
**Pull request by h-michael**
do #869 issue.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thanks!

**Comment by birkenfeld** [comment]
Not sure this was a good change. It added more LOC, and the API should actually logically change in the other direction (return some `impl Iterator` or `Box<Iterator>`).

(Also, `vec::Vec` is just `Vec`, please.)

**Comment by kngwyu** [comment]
> Also, vec::Vec is just Vec, please.

I'll fix it later.

> return some impl Iterator or Box<Iterator>

I don't think such abstraction is useful to just return multiple matches, since concatenating iterators to Vec is slower than `Vec::append`.

**Comment by birkenfeld** [comment]
> I don't think such abstraction is useful to just return multiple matches, since concatenating iterators to Vec is slower than Vec::append.

Sure. The thing I remember is just that sometimes we only need "the first match"; using iterators would ensure that we don't do unused work. But of course not with the "create a Vec and then call `into_iter` before returning" strategy that was used before this change :)

**Pull request merged**
