### PR TITLE
Mark rust source file as non-executable.

### PR DESCRIPTION
**Pull request by hvenev**
Fixes issue #1067

It would be nice if you can backport this to beta as well.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thank you!

> It would be nice if you can backport this to beta as well.

What does *beta* mean?
2.0.*?

**Comment by hvenev** [comment]
I mean rustc 1.38.

**Comment by kngwyu** [comment]
Now racer supports only nightly :scream: , sorry.

**Comment by hvenev** [comment]
A version of racer is included in the rustc beta release tarball. Can you include this fix in the version that gets in the stable tarball?

**Comment by h-michael** [comment]
@hvenev To guess, isn't it a racer that goes in with rls dependencies?

**Pull request merged**
