### PR TITLE
migrate to cargo-metadata

### PR DESCRIPTION
**Pull request by kngwyu**
To remove cargo dependency.

### CODE REVIEW

**Comment by kngwyu** [comment]
benchmark result
before:
```
test completes_rand  ... bench:  99,061,180 ns/iter (+/- 5,382,882)
test completes_rayon ... bench:  14,012,226 ns/iter (+/- 2,249,149)
```
after: 
```
test completes_rand  ... bench:  66,768,857 ns/iter (+/- 3,299,046)
test completes_rayon ... bench:  29,467,723 ns/iter (+/- 3,618,528)
```

Since I couldn't see a serious performance issue here, I decided to merge this PR.

**Comment by birkenfeld** [comment]
A 100% worse number on `rayon` is not serious?

**Comment by kngwyu** [comment]
@birkenfeld 
Now we have a lot of issues around installing because of cargo(#927, #919), and it's more serious.
Indeed using subprocess make the program slower, but I think 0.01s delay is acceptable.
In addition, since we call `cargo metadata` only once in a session, it shouldn't be a large bottleneck.

**Comment by birkenfeld** [comment]
Well, for many users each completion is a new session. But as long as it's a constant offset that should be ok, at least as long as it doesn't dominate the processing time.

**Pull request merged**
