### PR TITLE
bump rustc-ap crates to v712

### PR DESCRIPTION
**Pull request by calebcartwright**
Need to bump these again to fix broken toolstate issues with rustfmt and RLS

refs https://github.com/rust-lang/rust/issues/83460
refs https://github.com/rust-lang/rust/issues/83459

r? @kngwyu or @Xanewok

### CODE REVIEW

**Review by kngwyu — APPROVED** [review]
Thanks!

**Comment by kngwyu** [comment]
I'll release a new version when I get home.

**Comment by Xanewok** [comment]
@calebcartwright Thanks a lot for making the patch yourself in the end! Sorry for the delay.

**Comment by calebcartwright** [comment]
> I'll release a new version when I get home.

@kngwyu - Thank you! 

> @calebcartwright Thanks a lot for making the patch yourself in the end! Sorry for the delay.

@Xanewok - No worries, I found myself with a little bandwidth and figured I'd go ahead and submit since it was an easy change

**Comment by kngwyu** [comment]
Released v2.1.45

**Pull request merged**
