### PR TITLE
bump rustc-ap* to v679

### PR DESCRIPTION
**Pull request by calebcartwright**
We're planning to release a new version of rustfmt that also includes a bump of the rustc-ap-* crates to v679, so opening this to keep things synchronized

### CODE REVIEW

**Comment by calebcartwright** [comment]
Will bump the toolchain as well

**Comment by dtolnay** [comment]
Windows CI failed (https://ci.appveyor.com/project/TedDriggs/racer-xr5g5/builds/35374255/job/2ygcxfq0t9ds2cqg), but it appears the same tests are failing the same way on master too right now (https://ci.appveyor.com/project/TedDriggs/racer-xr5g5/branch/master/job/jl8rg68a5aai9971), so unrelated to this PR.

**Comment by calebcartwright** [comment]
> so unrelated to this PR.

Correct. @Xanewok got the tests passing again not too long ago but seems to be a caching issue on Appveyor (refs https://github.com/racer-rust/racer/pull/1130#issuecomment-687226537)

**Review by kngwyu — APPROVED** [review]
Thanks, sorry for my delay!

**Comment by calebcartwright** [comment]
No worries, and thank you!

**Comment by kngwyu** [comment]
Released 2.1.39

**Pull request merged**
